name: day03
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  ffi: ^2.1.0
  lints: ^3.0.0 
  test: ^1.24.0
